version: 1.0.{build}
image: Visual Studio 2017 RC
configuration: Release
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: nuget restore
after_build:
- cmd: nuget pack BuildTools\RxProperty.nuspec
build:
  verbosity: minimal
artifacts:
- path: '**\RxProperty.*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: VPVcOZWKhKQ9Bq5KTvwZC2G4j6GoOvms0/ViiOuWJl5VMahv5iMmc79BhbtC34l5