version: 1.0.{build}
image: Visual Studio 2017 RC
configuration: Release
platform: Any CPU
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
artifacts:
- path: 'BuildTools\ReactivePropertyOnly.*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: VPVcOZWKhKQ9Bq5KTvwZC2G4j6GoOvms0/ViiOuWJl5VMahv5iMmc79BhbtC34l5